
when(DeployedWebapp deployedWar, Tomcat tc, Host host, ConsulIO consulio)
#   deployedWar "is deployed on tomcat" tc
#   tc "is on host" host 
#   consulio "is on host" host
# then
#   add httpCheck on consul for webapp context
#        - id: <<servers/host>>/consulio/<<tomcat>>-<<deployedWar>>-httpcheck
#          type: ConsulIOHttpCheck
#          httpURL: http://localhost:<<tomcat.port>>/<<deployedWar>>/ping.html
